
steps:
  - name: "gcr.io/cloud-builders/docker"
    script: |
      docker build -t us-central1-docker.pkg.dev/kaelance-8a366/valid/valid-api:latest .
    automapSubstitutions: true  # Not strictly necessary with defined substitutions
secretEnv: ['DATABASE_URL', 'FLW_SECRET_HASH', 'FLW_PUBLIC_KEY', 'FLW_SECRET_KEY', 'PORT']
secrets:
  - kmsKeyName: projects/kaelance-8a366/locations/global/keyRings/YOUR_KEYRING/cryptoKeys/YOUR_KEY
    secretEnv:
      DATABASE_URL: projects/kaelance-8a366/secrets/DATABASE_URL/versions/latest
      FLW_SECRET_HASH: projects/kaelance-8a366/secrets/FLW_SECRET_HASH/versions/latest
      FLW_PUBLIC_KEY: projects/kaelance-8a366/secrets/FLW_PUBLIC_KEY/versions/latest
      FLW_SECRET_KEY: projects/kaelance-8a366/secrets/FLW_SECRET_KEY/versions/latest
      PORT: projects/kaelance-8a366/secrets/PORT/versions/latest
images:
  - "us-central1-docker.pkg.dev/kaelance-8a366/valid/valid-api:latest"


  - name: 'gcr.io/cloud-builders/gcloud'
    script: |
    gcloud run deploy cloudrunservice --image us-central1-docker.pkg.dev/kaelance-8a366/valid/valid-api:latest --region us-central1 --platform managed  --allow-unauthenticated