steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/valid", "."]
    secretEnv: ["DATABASE_URL", "API_KEY"] # Replace with your own secrets

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/valid"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - your-service-name
      - --image=gcr.io/${PROJECT_ID}/valid
      - --region=YOUR_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --update-secrets=/app/.env=DATABASE_URL:latest,API_KEY:latest

images:
  - "gcr.io/${PROJECT_ID}/valid"

secrets:
  - kmsKeyName: projects/${PROJECT_ID}/locations/global/keyRings/YOUR_KEY_RING/cryptoKeys/YOUR_KEY
    secretEnv:
      DATABASE_URL: "projects/${PROJECT_ID}/secrets/DATABASE_URL/versions/latest"
      API_KEY: "projects/${PROJECT_ID}/secrets/API_KEY/versions/latest"
