options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Set up environment variables from secrets
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/valid-api:$COMMIT_SHA", "."]

  # Step 3: Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/valid-api:$COMMIT_SHA"]

  # Step 4: Deploy container image to Cloud Run
  # Step 4: Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "valid-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/valid-api:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--timeout"
      - "1600s" # Increase the timeout to 10 minutes (600 seconds)

