version: "4.35.1"

services:
  valid:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLW_SECRET_HASH=${FLW_SECRET_HASH}
      - FLW_PUBLIC_KEY=${FLW_PUBLIC_KEY}
      - FLW_SECRET_KEY=${FLW_SECRET_KEY}
      - PORT=${PORT:-8080} # Fallback to 8080 if PORT is unset
    ports:
      - "${PORT:-8080}:${PORT:-8080}" # Match the fallback port
    env_file:
      - .env
